backend:
  name: github
  repo: ux-at-icfnext/herc # Path to your GitHub repository
  netlify.configure({'site_id': herc-library.netlify.app);
  # optional, defaults to master
  branch: main

media_folder: "assets/img/uploads"

collections:
  - label: "Pattern Specifications"
    name: "Pattern Specifications"
    folder: "pages/patterns"
    create: true
    fields:
      - {label: "layout", name: "layout", widget: "hidden", default: "patterns" }
      - {label: "Page Title", name: "title", widget: "string", hint: "Please use title case format", required: true }
      - {label: "Page location", name: "permalink", widget: "string", hint: "Page url, should start with '/'", required: true}
      - {label: "Short description", name: "description", widget: "markdown", required: false}
      - {label: "Page group", name: "parent", widget: "string", hint: "if this pattern is part of a group, enter the group name", required: false }
      - {label: "Category", name: "category", widget: "hidden", default: "pattern" }
      - {label: "Specifications", name: "specification", widget: "markdown", required: false }
      - label: "Content Specifications"
        name: "schema"
        widget: "list"
        fields:
          - {label: "Field name", name: "fieldname", widget: "text", required: true }
          - {label: "Field Type", name: "type", widget: "text", required: false }
          - {label: "Class", name: "class", widget: "text", required: false }
          - {label: "Required", name: "required", widget: "boolean", required: false }
          - {label: "Content Specs", name: "content", widget: "text", required: false }
          - {label: "Example content", name: "example", widget: "text", required: false }
          - {label: "Notes", name: "notes", widget: "text", required: false }
      - {label: "More information", name: "body", widget: "markdown", hint: "use this if more information is needed to describe the pattern.", required: false}
          

