backend:
  name: github
  repo: ux-at-icfnext/herc # Path to your GitHub repository
  netlify.configure({'site_id': herc-library.netlify.app);
  # optional, defaults to master
  branch: main

media_folder: "assets/img/uploads"